import React from 'react';
import Head from 'next/head';

const MetaHead = () => {
  return (
    <React.Fragment>
      <Head>
        <title>Resume-brilianrn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </React.Fragment>
  );
};

export default MetaHead;
